package com.luoyk.toolbox.panel.mysql;

import com.luoyk.toolbox.api.SqlResult;
import com.luoyk.toolbox.utils.Common;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class DataTable {
    private JPanel panel;
    private JTable table;
    private JLabel sql;

    private final String[] columnNames = new String[0];
    private final String[][] data = new String[0][0];

    private final DefaultTableModel defaultTableModel = new DefaultTableModel(data, columnNames);

    public JPanel getPanel() {
        return panel;
    }

    public DataTable() {
    }

    public void init(SqlResult sqlResult) {

        final String[] columnNames = sqlResult.getColumnNames();

        defaultTableModel.setDataVector(sqlResult.getData(), columnNames);
        table.getTableHeader().setReorderingAllowed(false);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.setModel(defaultTableModel);
        table.setRowHeight(Common.fontSize + Common.fontSize / 2);

        for (int i = 0; i < columnNames.length; i++) {
            int width = columnNames[i].length() * Common.fontSize;
            table.getColumnModel().getColumn(i).setPreferredWidth(width);
        }

        setSqlText(sqlResult.getSql() + "    " +
                Common.language.getString("mysql_data_table_sql_time") + " " + sqlResult.getTime() + Common.language.getString("mysql_data_table_sql_time_ms") + "    " +
                Common.language.getString("mysql_data_table_sql_count") + " " + sqlResult.getData().length);
    }

    public void clearTable() {
        defaultTableModel.setDataVector(this.data, this.columnNames);
    }

    public void setSqlText(String text) {
        sql.setText(text);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        sql = new JLabel();
        sql.setText("Label");
        panel.add(sql, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, BorderLayout.CENTER);
        table = new JTable();
        scrollPane1.setViewportView(table);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
