package com.luoyk.toolbox.utils;

import java.util.*;
import java.util.stream.Collectors;

public class MysqlWord {

    private static final Set<String> WORD_SET;
    private static final List<String> TYPE_LIST;
    private static final Map<String, Set<String>> WORD_MAP;

    static {
        String keyWord = "ACCESSIBLE\n" +
                "ACCOUNT\n" +
                "ACTION\n" +
                "ACTIVE\n" +
                "ADD\n" +
                "ADMIN\n" +
                "AFTER\n" +
                "AGAINST\n" +
                "AGGREGATE\n" +
                "ALGORITHM\n" +
                "ALL\n" +
                "ALTER\n" +
                "ALWAYS\n" +
                "ANALYSE\n" +
                "ANALYZE\n" +
                "AND\n" +
                "ANY\n" +
                "ARRAY\n" +
                "AS\n" +
                "ASC\n" +
                "ASCII\n" +
                "ASENSITIVE\n" +
                "AT\n" +
                "ATTRIBUTE\n" +
                "AUTOEXTEND_SIZE\n" +
                "AUTO_INCREMENT\n" +
                "AVG\n" +
                "AVG_ROW_LENGTH\n" +
                "BACKUP\n" +
                "BEFORE\n" +
                "BEGIN\n" +
                "BETWEEN\n" +
                "BIGINT\n" +
                "BINARY\n" +
                "BINLOG\n" +
                "BIT\n" +
                "BLOB\n" +
                "BLOCK\n" +
                "BOOL\n" +
                "BOOLEAN\n" +
                "BOTH\n" +
                "BTREE\n" +
                "BUCKETS\n" +
                "BY\n" +
                "BYTE\n" +
                "CACHE\n" +
                "CALL\n" +
                "CASCADE\n" +
                "CASCADED\n" +
                "CASE\n" +
                "CATALOG_NAME\n" +
                "CHAIN\n" +
                "CHANGE\n" +
                "CHANGED\n" +
                "CHANNEL\n" +
                "CHAR\n" +
                "CHARACTER\n" +
                "CHARSET\n" +
                "CHECK\n" +
                "CHECKSUM\n" +
                "CIPHER\n" +
                "CLASS_ORIGIN\n" +
                "CLIENT\n" +
                "CLONE\n" +
                "CLOSE\n" +
                "COALESCE\n" +
                "CODE\n" +
                "COLLATE\n" +
                "COLLATION\n" +
                "COLUMN\n" +
                "COLUMNS\n" +
                "COLUMN_FORMAT\n" +
                "COLUMN_NAME\n" +
                "COMMENT\n" +
                "COMMIT\n" +
                "COMMITTED\n" +
                "COMPACT\n" +
                "COMPLETION\n" +
                "COMPONENT\n" +
                "COMPRESSED\n" +
                "COMPRESSION\n" +
                "CONCURRENT\n" +
                "CONDITION\n" +
                "CONNECTION\n" +
                "CONSISTENT\n" +
                "CONSTRAINT\n" +
                "CONSTRAINT_CATALOG\n" +
                "CONSTRAINT_NAME\n" +
                "CONSTRAINT_SCHEMA\n" +
                "CONTAINS\n" +
                "CONTEXT\n" +
                "CONTINUE\n" +
                "CONVERT\n" +
                "CPU\n" +
                "CREATE\n" +
                "CROSS\n" +
                "CUBE\n" +
                "CUME_DIST\n" +
                "CURRENT\n" +
                "CURRENT_DATE\n" +
                "CURRENT_TIME\n" +
                "CURRENT_TIMESTAMP\n" +
                "CURRENT_USER\n" +
                "CURSOR\n" +
                "CURSOR_NAME\n" +
                "DATA\n" +
                "DATABASE\n" +
                "DATABASES\n" +
                "DATAFILE\n" +
                "DATE\n" +
                "DATETIME\n" +
                "DAY\n" +
                "DAY_HOUR\n" +
                "DAY_MICROSECOND\n" +
                "DAY_MINUTE\n" +
                "DAY_SECOND\n" +
                "DEALLOCATE\n" +
                "DEC\n" +
                "DECIMAL\n" +
                "DECLARE\n" +
                "DEFAULT\n" +
                "DEFAULT_AUTH\n" +
                "DEFINER\n" +
                "DEFINITION\n" +
                "DELAYED\n" +
                "DELAY_KEY_WRITE\n" +
                "DELETE\n" +
                "DENSE_RANK\n" +
                "DESC\n" +
                "DESCRIBE\n" +
                "DESCRIPTION\n" +
                "DES_KEY_FILE\n" +
                "DETERMINISTIC\n" +
                "DIAGNOSTICS\n" +
                "DIRECTORY\n" +
                "DISABLE\n" +
                "DISCARD\n" +
                "DISK\n" +
                "DISTINCT\n" +
                "DISTINCTROW\n" +
                "DIV\n" +
                "DO\n" +
                "DOUBLE\n" +
                "DROP\n" +
                "DUAL\n" +
                "DUMPFILE\n" +
                "DUPLICATE\n" +
                "DYNAMIC\n" +
                "EACH\n" +
                "ELSE\n" +
                "ELSEIF\n" +
                "EMPTY\n" +
                "ENABLE\n" +
                "ENCLOSED\n" +
                "ENCRYPTION\n" +
                "END\n" +
                "ENDS\n" +
                "ENFORCED\n" +
                "ENGINE\n" +
                "ENGINES\n" +
                "ENGINE_ATTRIBUTE\n" +
                "ENUM\n" +
                "ERROR\n" +
                "ERRORS\n" +
                "ESCAPE\n" +
                "ESCAPED\n" +
                "EVENT\n" +
                "EVENTS\n" +
                "EVERY\n" +
                "EXCEPT\n" +
                "EXCHANGE\n" +
                "EXCLUDE\n" +
                "EXECUTE\n" +
                "EXISTS\n" +
                "EXIT\n" +
                "EXPANSION\n" +
                "EXPIRE\n" +
                "EXPLAIN\n" +
                "EXPORT\n" +
                "EXTENDED\n" +
                "EXTENT_SIZE\n" +
                "FAILED_LOGIN_ATTEMPTS\n" +
                "FALSE\n" +
                "FAST\n" +
                "FAULTS\n" +
                "FETCH\n" +
                "FIELDS\n" +
                "FILE\n" +
                "FILE_BLOCK_SIZE\n" +
                "FILTER\n" +
                "FIRST\n" +
                "FIRST_VALUE\n" +
                "FIXED\n" +
                "FLOAT\n" +
                "FLOAT4\n" +
                "FLOAT8\n" +
                "FLUSH\n" +
                "FOLLOWING\n" +
                "FOLLOWS\n" +
                "FOR\n" +
                "FORCE\n" +
                "FOREIGN\n" +
                "FORMAT\n" +
                "FOUND\n" +
                "FROM\n" +
                "FULL\n" +
                "FULLTEXT\n" +
                "FUNCTION\n" +
                "GENERAL\n" +
                "GENERATED\n" +
                "GEOMCOLLECTION\n" +
                "GEOMETRY\n" +
                "GEOMETRYCOLLECTION\n" +
                "GET\n" +
                "GET_FORMAT\n" +
                "GET_MASTER_PUBLIC_KEY\n" +
                "GLOBAL\n" +
                "GRANT\n" +
                "GRANTS\n" +
                "GROUP\n" +
                "GROUPING\n" +
                "GROUPS\n" +
                "GROUP_REPLICATION\n" +
                "HANDLER\n" +
                "HASH\n" +
                "HAVING\n" +
                "HELP\n" +
                "HIGH_PRIORITY\n" +
                "HISTOGRAM\n" +
                "HISTORY\n" +
                "HOST\n" +
                "HOSTS\n" +
                "HOUR\n" +
                "HOUR_MICROSECOND\n" +
                "HOUR_MINUTE\n" +
                "HOUR_SECOND\n" +
                "IDENTIFIED\n" +
                "IF\n" +
                "IGNORE\n" +
                "IGNORE_SERVER_IDS\n" +
                "IMPORT\n" +
                "IN\n" +
                "INACTIVE\n" +
                "INDEX\n" +
                "INDEXES\n" +
                "INFILE\n" +
                "INITIAL_SIZE\n" +
                "INNER\n" +
                "INOUT\n" +
                "INSENSITIVE\n" +
                "INSERT\n" +
                "INSERT_METHOD\n" +
                "INSTALL\n" +
                "INSTANCE\n" +
                "INT\n" +
                "INT1\n" +
                "INT2\n" +
                "INT3\n" +
                "INT4\n" +
                "INT8\n" +
                "INTEGER\n" +
                "INTERVAL\n" +
                "INTO\n" +
                "INVISIBLE\n" +
                "INVOKER\n" +
                "IO\n" +
                "IO_AFTER_GTIDS\n" +
                "IO_BEFORE_GTIDS\n" +
                "IO_THREAD\n" +
                "IPC\n" +
                "IS\n" +
                "ISOLATION\n" +
                "ISSUER\n" +
                "ITERATE\n" +
                "JOIN\n" +
                "JSON\n" +
                "JSON_TABLE\n" +
                "JSON_VALUE\n" +
                "KEY\n" +
                "KEYS\n" +
                "KEY_BLOCK_SIZE\n" +
                "KILL\n" +
                "LAG\n" +
                "LANGUAGE\n" +
                "LAST\n" +
                "LAST_VALUE\n" +
                "LATERAL\n" +
                "LEAD\n" +
                "LEADING\n" +
                "LEAVE\n" +
                "LEAVES\n" +
                "LEFT\n" +
                "LESS\n" +
                "LEVEL\n" +
                "LIKE\n" +
                "LIMIT\n" +
                "LINEAR\n" +
                "LINES\n" +
                "LINESTRING\n" +
                "LIST\n" +
                "LOAD\n" +
                "LOCAL\n" +
                "LOCALTIME\n" +
                "LOCALTIMESTAMP\n" +
                "LOCK\n" +
                "LOCKED\n" +
                "LOCKS\n" +
                "LOGFILE\n" +
                "LOGS\n" +
                "LONG\n" +
                "LONGBLOB\n" +
                "LONGTEXT\n" +
                "LOOP\n" +
                "LOW_PRIORITY\n" +
                "MANAGED\n" +
                "MASTER\n" +
                "MASTER_AUTO_POSITION\n" +
                "MASTER_BIND\n" +
                "MASTER_COMPRESSION_ALGORITHMS\n" +
                "MASTER_CONNECT_RETRY\n" +
                "MASTER_DELAY\n" +
                "MASTER_HEARTBEAT_PERIOD\n" +
                "MASTER_HOST\n" +
                "MASTER_LOG_FILE\n" +
                "MASTER_LOG_POS\n" +
                "MASTER_PASSWORD\n" +
                "MASTER_PORT\n" +
                "MASTER_PUBLIC_KEY_PATH\n" +
                "MASTER_RETRY_COUNT\n" +
                "MASTER_SERVER_ID\n" +
                "MASTER_SSL\n" +
                "MASTER_SSL_CA\n" +
                "MASTER_SSL_CAPATH\n" +
                "MASTER_SSL_CERT\n" +
                "MASTER_SSL_CIPHER\n" +
                "MASTER_SSL_CRL\n" +
                "MASTER_SSL_CRLPATH\n" +
                "MASTER_SSL_KEY\n" +
                "MASTER_SSL_VERIFY_SERVER_CERT\n" +
                "MASTER_TLS_CIPHERSUITES\n" +
                "MASTER_TLS_VERSION\n" +
                "MASTER_USER\n" +
                "MASTER_ZSTD_COMPRESSION_LEVEL\n" +
                "MATCH\n" +
                "MAXVALUE\n" +
                "MAX_CONNECTIONS_PER_HOUR\n" +
                "MAX_QUERIES_PER_HOUR\n" +
                "MAX_ROWS\n" +
                "MAX_SIZE\n" +
                "MAX_UPDATES_PER_HOUR\n" +
                "MAX_USER_CONNECTIONS\n" +
                "MEDIUM\n" +
                "MEDIUMBLOB\n" +
                "MEDIUMINT\n" +
                "MEDIUMTEXT\n" +
                "MEMBER\n" +
                "MEMORY\n" +
                "MERGE\n" +
                "MESSAGE_TEXT\n" +
                "MICROSECOND\n" +
                "MIDDLEINT\n" +
                "MIGRATE\n" +
                "MINUTE\n" +
                "MINUTE_MICROSECOND\n" +
                "MINUTE_SECOND\n" +
                "MIN_ROWS\n" +
                "MOD\n" +
                "MODE\n" +
                "MODIFIES\n" +
                "MODIFY\n" +
                "MONTH\n" +
                "MULTILINESTRING\n" +
                "MULTIPOINT\n" +
                "MULTIPOLYGON\n" +
                "MUTEX\n" +
                "MYSQL_ERRNO\n" +
                "NAME\n" +
                "NAMES\n" +
                "NATIONAL\n" +
                "NATURAL\n" +
                "NCHAR\n" +
                "NDB\n" +
                "NDBCLUSTER\n" +
                "NESTED\n" +
                "NETWORK_NAMESPACE\n" +
                "NEVER\n" +
                "NEW\n" +
                "NEXT\n" +
                "NO\n" +
                "NODEGROUP\n" +
                "NONE\n" +
                "NOT\n" +
                "NOWAIT\n" +
                "NO_WAIT\n" +
                "NO_WRITE_TO_BINLOG\n" +
                "NTH_VALUE\n" +
                "NTILE\n" +
                "NULL\n" +
                "NULLS\n" +
                "NUMBER\n" +
                "NUMERIC\n" +
                "NVARCHAR\n" +
                "OF\n" +
                "OFF\n" +
                "OFFSET\n" +
                "OJ\n" +
                "OLD\n" +
                "ON\n" +
                "ONE\n" +
                "ONLY\n" +
                "OPEN\n" +
                "OPTIMIZE\n" +
                "OPTIMIZER_COSTS\n" +
                "OPTION\n" +
                "OPTIONAL\n" +
                "OPTIONALLY\n" +
                "OPTIONS\n" +
                "OR\n" +
                "ORDER\n" +
                "ORDINALITY\n" +
                "ORGANIZATION\n" +
                "OTHERS\n" +
                "OUT\n" +
                "OUTER\n" +
                "OUTFILE\n" +
                "OVER\n" +
                "OWNER\n" +
                "PACK_KEYS\n" +
                "PAGE\n" +
                "PARSER\n" +
                "PARTIAL\n" +
                "PARTITION\n" +
                "PARTITIONING\n" +
                "PARTITIONS\n" +
                "PASSWORD\n" +
                "PASSWORD_LOCK_TIME\n" +
                "PATH\n" +
                "PERCENT_RANK\n" +
                "PERSIST\n" +
                "PERSIST_ONLY\n" +
                "PHASE\n" +
                "PLUGIN\n" +
                "PLUGINS\n" +
                "PLUGIN_DIR\n" +
                "POINT\n" +
                "POLYGON\n" +
                "PORT\n" +
                "PRECEDES\n" +
                "PRECEDING\n" +
                "PRECISION\n" +
                "PREPARE\n" +
                "PRESERVE\n" +
                "PREV\n" +
                "PRIMARY\n" +
                "PRIVILEGES\n" +
                "PRIVILEGE_CHECKS_USER\n" +
                "PROCEDURE\n" +
                "PROCESS\n" +
                "PROCESSLIST\n" +
                "PROFILE\n" +
                "PROFILES\n" +
                "PROXY\n" +
                "PURGE\n" +
                "QUARTER\n" +
                "QUERY\n" +
                "QUICK\n" +
                "RANDOM\n" +
                "RANGE\n" +
                "RANK\n" +
                "READ\n" +
                "READS\n" +
                "READ_ONLY\n" +
                "READ_WRITE\n" +
                "REAL\n" +
                "REBUILD\n" +
                "RECOVER\n" +
                "RECURSIVE\n" +
                "REDOFILE\n" +
                "REDO_BUFFER_SIZE\n" +
                "REDUNDANT\n" +
                "REFERENCE\n" +
                "REFERENCES\n" +
                "REGEXP\n" +
                "RELAY\n" +
                "RELAYLOG\n" +
                "RELAY_LOG_FILE\n" +
                "RELAY_LOG_POS\n" +
                "RELAY_THREAD\n" +
                "RELEASE\n" +
                "RELOAD\n" +
                "REMOTE\n" +
                "REMOVE\n" +
                "RENAME\n" +
                "REORGANIZE\n" +
                "REPAIR\n" +
                "REPEAT\n" +
                "REPEATABLE\n" +
                "REPLACE\n" +
                "REPLICATE_DO_DB\n" +
                "REPLICATE_DO_TABLE\n" +
                "REPLICATE_IGNORE_DB\n" +
                "REPLICATE_IGNORE_TABLE\n" +
                "REPLICATE_REWRITE_DB\n" +
                "REPLICATE_WILD_DO_TABLE\n" +
                "REPLICATE_WILD_IGNORE_TABLE\n" +
                "REPLICATION\n" +
                "REQUIRE\n" +
                "REQUIRE_ROW_FORMAT\n" +
                "RESET\n" +
                "RESIGNAL\n" +
                "RESOURCE\n" +
                "RESPECT\n" +
                "RESTART\n" +
                "RESTORE\n" +
                "RESTRICT\n" +
                "RESUME\n" +
                "RETAIN\n" +
                "RETURN\n" +
                "RETURNED_SQLSTATE\n" +
                "RETURNING\n" +
                "RETURNS\n" +
                "REUSE\n" +
                "REVERSE\n" +
                "REVOKE\n" +
                "RIGHT\n" +
                "RLIKE\n" +
                "ROLE\n" +
                "ROLLBACK\n" +
                "ROLLUP\n" +
                "ROTATE\n" +
                "ROUTINE\n" +
                "ROW\n" +
                "ROWS\n" +
                "ROW_COUNT\n" +
                "ROW_FORMAT\n" +
                "ROW_NUMBER\n" +
                "RTREE\n" +
                "SAVEPOINT\n" +
                "SCHEDULE\n" +
                "SCHEMA\n" +
                "SCHEMAS\n" +
                "SCHEMA_NAME\n" +
                "SECOND\n" +
                "SECONDARY\n" +
                "SECONDARY_ENGINE\n" +
                "SECONDARY_ENGINE_ATTRIBUTE\n" +
                "SECONDARY_LOAD\n" +
                "SECONDARY_UNLOAD\n" +
                "SECOND_MICROSECOND\n" +
                "SECURITY\n" +
                "SELECT\n" +
                "SENSITIVE\n" +
                "SEPARATOR\n" +
                "SERIAL\n" +
                "SERIALIZABLE\n" +
                "SERVER\n" +
                "SESSION\n" +
                "SET\n" +
                "SHARE\n" +
                "SHOW\n" +
                "SHUTDOWN\n" +
                "SIGNAL\n" +
                "SIGNED\n" +
                "SIMPLE\n" +
                "SKIP\n" +
                "SLAVE\n" +
                "SLOW\n" +
                "SMALLINT\n" +
                "SNAPSHOT\n" +
                "SOCKET\n" +
                "SOME\n" +
                "SONAME\n" +
                "SOUNDS\n" +
                "SOURCE\n" +
                "SPATIAL\n" +
                "SPECIFIC\n" +
                "SQL\n" +
                "SQLEXCEPTION\n" +
                "SQLSTATE\n" +
                "SQLWARNING\n" +
                "SQL_AFTER_GTIDS\n" +
                "SQL_AFTER_MTS_GAPS\n" +
                "SQL_BEFORE_GTIDS\n" +
                "SQL_BIG_RESULT\n" +
                "SQL_BUFFER_RESULT\n" +
                "SQL_CACHE\n" +
                "SQL_CALC_FOUND_ROWS\n" +
                "SQL_NO_CACHE\n" +
                "SQL_SMALL_RESULT\n" +
                "SQL_THREAD\n" +
                "SQL_TSI_DAY\n" +
                "SQL_TSI_HOUR\n" +
                "SQL_TSI_MINUTE\n" +
                "SQL_TSI_MONTH\n" +
                "SQL_TSI_QUARTER\n" +
                "SQL_TSI_SECOND\n" +
                "SQL_TSI_WEEK\n" +
                "SQL_TSI_YEAR\n" +
                "SRID\n" +
                "SSL\n" +
                "STACKED\n" +
                "START\n" +
                "STARTING\n" +
                "STARTS\n" +
                "STATS_AUTO_RECALC\n" +
                "STATS_PERSISTENT\n" +
                "STATS_SAMPLE_PAGES\n" +
                "STATUS\n" +
                "STOP\n" +
                "STORAGE\n" +
                "STORED\n" +
                "STRAIGHT_JOIN\n" +
                "STREAM\n" +
                "STRING\n" +
                "SUBCLASS_ORIGIN\n" +
                "SUBJECT\n" +
                "SUBPARTITION\n" +
                "SUBPARTITIONS\n" +
                "SUPER\n" +
                "SUSPEND\n" +
                "SWAPS\n" +
                "SWITCHES\n" +
                "SYSTEM\n" +
                "TABLE\n" +
                "TABLES\n" +
                "TABLESPACE\n" +
                "TABLE_CHECKSUM\n" +
                "TABLE_NAME\n" +
                "TEMPORARY\n" +
                "TEMPTABLE\n" +
                "TERMINATED\n" +
                "TEXT\n" +
                "THAN\n" +
                "THEN\n" +
                "THREAD_PRIORITY\n" +
                "TIES\n" +
                "TIME\n" +
                "TIMESTAMP\n" +
                "TIMESTAMPADD\n" +
                "TIMESTAMPDIFF\n" +
                "TINYBLOB\n" +
                "TINYINT\n" +
                "TINYTEXT\n" +
                "TLS\n" +
                "TO\n" +
                "TRAILING\n" +
                "TRANSACTION\n" +
                "TRIGGER\n" +
                "TRIGGERS\n" +
                "TRUE\n" +
                "TRUNCATE\n" +
                "TYPE\n" +
                "TYPES\n" +
                "UNBOUNDED\n" +
                "UNCOMMITTED\n" +
                "UNDEFINED\n" +
                "UNDO\n" +
                "UNDOFILE\n" +
                "UNDO_BUFFER_SIZE\n" +
                "UNICODE\n" +
                "UNINSTALL\n" +
                "UNION\n" +
                "UNIQUE\n" +
                "UNKNOWN\n" +
                "UNLOCK\n" +
                "UNSIGNED\n" +
                "UNTIL\n" +
                "UPDATE\n" +
                "UPGRADE\n" +
                "USAGE\n" +
                "USE\n" +
                "USER\n" +
                "USER_RESOURCES\n" +
                "USE_FRM\n" +
                "USING\n" +
                "UTC_DATE\n" +
                "UTC_TIME\n" +
                "UTC_TIMESTAMP\n" +
                "VALIDATION\n" +
                "VALUE\n" +
                "VALUES\n" +
                "VARBINARY\n" +
                "VARCHAR\n" +
                "VARCHARACTER\n" +
                "VARIABLES\n" +
                "VARYING\n" +
                "VCPU\n" +
                "VIEW\n" +
                "VIRTUAL\n" +
                "VISIBLE\n" +
                "WAIT\n" +
                "WARNINGS\n" +
                "WEEK\n" +
                "WEIGHT_STRING\n" +
                "WHEN\n" +
                "WHERE\n" +
                "WHILE\n" +
                "WINDOW\n" +
                "WITH\n" +
                "WITHOUT\n" +
                "WORK\n" +
                "WRAPPER\n" +
                "WRITE\n" +
                "X509\n" +
                "XA\n" +
                "XID\n" +
                "XML\n" +
                "XOR\n" +
                "YEAR\n" +
                "YEAR_MONTH\n" +
                "ZEROFILL";

        String typeWord = "INTEGER\n" +
                "INT\n" +
                "SMALLINT\n" +
                "TINYINT\n" +
                "MEDIUMINT\n" +
                "BIGINT\n" +
                "DECIMAL\n" +
                "NUMERIC\n" +
                "FLOAT\n" +
                "DOUBLE\n" +
                "BIT\n" +
                "DATE\n" +
                "DATETIME\n" +
                "TIMESTAMP\n" +
                "CHAR\n" +
                "VARCHAR\n" +
                "BLOB\n" +
                "TEXT\n" +
                "ENUM\n" +
                "SET\n" +
                "JSON";

        WORD_SET = Arrays.stream(keyWord.split("\n")).collect(Collectors.toSet());

        WORD_MAP = WORD_SET.stream().collect(Collectors.groupingBy(str -> str.substring(0, 1), Collectors.toSet()));

        TYPE_LIST = Arrays.stream(typeWord.split("\n")).collect(Collectors.toList());
    }

    public static Set<String> getWordSet() {
        return WORD_SET;
    }

    public static boolean isWord(String str) {
        return Optional.ofNullable(str)
                .filter(s -> str.length() != 0)
                .map(s -> str.substring(0, 1))
                .map(WORD_MAP::get)
                .map(set -> set.contains(str))
                .orElse(false);
    }

    public static List<String> typeList() {
        return TYPE_LIST;
    }

}
